FROM ubuntu:18.04 as builder

RUN apt install --no-install-recommends -y \
        gettext \
        build-essential \
        autoconf libtool \
        libpcre3-dev asciidoc \
        xmlto \
        libev-dev \
        libc-ares-dev \
        automake \
        libmbedtls-dev \
        libsodium-dev