version: "2.4"
services:
  shadowsocks:
    image: eutial/shadowsocks-libev
    container_name: shadowsocks-libev
    volumes:
      - "$PWD/config.json:/etc/shadowsocks-libev/config.json"
    networks:
      - interloop
  
  obfs:
    image: eutial/simple-obfs
    container_name: simple-obfs
    ports:
      - "443:443"
      - "443:443/udp"
    volumes:
      - "$PWD/config.json:/etc/simple-obfs/config.json"
    depends_on:
      - shadowsocks
    networks:
      - interloop

networks:
  interloop:
    driver: bridge