version: "2.4"
services:
  shadowsocks:
    image: eutial/shadowsocks-libev
    container_name: shadowsocks-libev
    ports:
      - "18965:18965/udp"
    volumes:
      - "$PWD/libev.json:/etc/shadowsocks-libev/config.json"
    networks:
      - interloop
  
  obfs:
    image: eutial/simple-obfs
    container_name: simple-obfs
    ports:
      - "18965:18965"
    volumes:
      - "$PWD/obfs.json:/etc/simple-obfs/config.json"
    depends_on:
      - shadowsocks
    networks:
      - interloop

networks:
  interloop:
    driver: bridge